### ISSUE TITLE
authentication & encryption of messages between nodes and coordinator 

### ISSUE THREAD

**Issue by profi248** [profi248/pluto#11]
After a lengthy discussion, we decided to encrypt all MQTT messages to not rely on potentially buggy and non-portable ACLs. After a lot of research, it seems like the best option is to generate two keypairs for nodes and coordinator, one for signing with Ed25519 and the second one for encryption using X25519. Keys will be generated one after another with a mnemonic-seeded PRNG. Pubkeys of coordinator will be hardcoded in nodes. Messages to coordinator can thus be encrypted from the beginning. On initial node authentication, both pubkeys will be sent in a message and stored on the coordinator. Hash of concatenated pubkeys could serve as a unique identifier of a node (node ID), used in MQTT topic name. 

Communication between nodes using MQTT worker could work by coordinator initially sending pubkeys of both nodes that want to communicate between each other. Those will then save that on their keychains and expect all messages between them to be encrypted and signed. Node ID also serves as a fingerprint of a node.

If every message was be signed anyway, there would be no need for sessions anymore.

**Comment by nebneb0703** [comment]
hmm do we even need to use Ed25519 keys at all anymore? We can use the HPKE protocol to sign/authenticate encrypted messages. 

For the auth protocol to work, you need to be able to perform a DH with the sender's static private key and recipient's static public key, which we were struggling to do with Ed25519 keys anyway. If all messages are encrypted via this protocol from the start, including to the coordinator, authenticity can be verified using HPKE messages.

**Comment by profi248** [comment]
i guess should would work just fine
